CREATE TABLE users (
 id UUID PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
 password_hash VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE user_roles (
 user_id UUID NOT NULL REFERENCES users(id), role VARCHAR(20) NOT NULL,
 PRIMARY KEY(user_id,role), CHECK (role IN ('CUSTOMER','SELLER','ADMIN'))
);
